### ISSUE TITLE
Tittensor et al. comparison

### ISSUE THREAD

**Issue by dmcglinn** [mcglinnlab/shark-ray-div#14]
Hey @EmmalineSheahan, I was looking at the Tittensor et al paper and they report that they have data on 480 non-oceanic shark species and 27 oceanic sharks. Can you remind me how many sharks do we have range data for and of those how many do we have phylo data for? Also do you think it would be useful to divide the dataset into oceanic and non-oceanic?

**Comment by dmcglinn** [comment]
I tracked down the Tittersor data a bit more and found that it came from the Global Shark Distribution Database: http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0019356.s001&type=supplementary

**Comment by EmmalineSheahan** [comment]
We have 511 sharks and 23 chimaeras for taxonomic richness, and out of that
we have 281 sharks and no chimaeras on the phylogeny. I don't really see
any major reason to separate them out by pelagic and coastal unless we were
interested in seeing what factors affect diversity aside from distance from
the coast. Most pelagic sharks take up huge ranges and also exhibit really
distant migratory patterns, so I'm thinking they in particular would be
really prone to that swiss cheese effect (if you look at Gavin's ranges for
species like the white shark, mako,  and blue shark, they span entire
oceans even though they probably aren't occupying every single part of that
range, so I don't know that we'd glean any really accurate information
about where exactly pelagic diversity hotspots are).

I also looked further into shark evolutionary history and sharks actually
emerged a lot earlier than I had presumed; the oldest shark species (and
Chondrichthyan in general) in the fossil record is Elegestolepis, which
came about 418-416 million years ago during the late Silurian. Sharks
diverged further during the Devonian and hit a kind of adaptive radiation
during the Carboniferous period, possibly because of the late Devonian mass
extinction. The late Silurian early Devonian climate was a greenhouse earth
with warm shallow seas (which makes sense to me since vascular terrestrial
plants hadn't quite taken off yet). The Elegestolepis fossil was found in
Siberia, and a lot of Devonian shark fossils are discovered in New
Brunswick, Canada, an area that used to be a part of Euramerica and was
more equatorial. So it seems like the Chondrichthyan ancestral niche was
warm and coastal and probably developed alongside the early Devonian reef
habitat, since most all of the fossils are found in prehistoric reef beds
that used to be covered by ancient seas.
